# Jekyll configuration for GitHub Pages
title: Computational Astrophysics Lab
description: NTU Computational Astrophysics Lab
url: "https://vivi235711.github.io"
baseurl: "/Calab-new-web.github.io"

# Build settings
markdown: kramdown
exclude:
  - .github/workflows/updates-pubs.yml
  - .github/workflows/jekyll-gh-pages.yml
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - _tools/export-bibtex.bib
  - _tools/bib_to_yml.py

# Ensure assets are served from root
relative_permalinks: false

plugins:
  - jekyll-paginate

permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: "/news/page:num/"

collections:
  members:
    output: false # 設定為 false，表示不生成獨立的成員頁面 (我們只需要列表)
    permalink: /members/:path/
  useful:
    output: false
    permalink: /useful/:path/
  courses:
    output: false # 課程通常不需要獨立頁面
    permalink: /courses/:path/
  projects:
    output: false # 專案細節將透過 Modal 呈現，不需要獨立頁面
    permalink: /projects/:path/

sass:
  # The style option controls the output format of the compiled CSS.
  style: compressed